#! /bin/sh

sxhkd &
compton &
ru &
polybar example &
feh --bg-fill Pictures/Bg/2e3440.png &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#5e81ac'
bspc config normal_border_color '#81a1c1'
