#! /bin/sh

sxhkd &
compton &
ru &
polybar example &
feh --bg-fill ~/Pictures/Bg/840.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#635196'
bspc config normal_border_color '#3f3a59'
